dataset_name: 'tartanair'
camera_params:
  image_height: 480
  image_width: 640
  fx: 320.0
  fy: 320.0
  cx: 320.0
  cy: 240.0
  png_depth_scale: 1.0
  crop_edge: 0
  depth_filter_near: 0.1
  depth_filter_far: 30.0
